spring.application.name=ch2502
server.port=8085 
spring.thymeleaf.cache=false 
spring.devtools.restart.enabled=false

spring.datasource.generate-unique-name=false

spring.mongodb.uri=mongodb+srv://atlasuser:${MONGODB_PASSWORD}@cluster0.p1txhp1.mongodb.net/tacoclouddb
